-- FUNCTION

select*FROM EMP WHERE MOD(EMPNO,2) <> 0;
select empno,ename,job from emp where job='MANAGER';
select*from emp where substr(hiredate,4,2)=09;
select sysdate-7 from dual;
SELECT HIREDATE, ROUND (HIREDATE, 'MONTH')  FROM EMP; 
SELECT HIREDATE, TRUNC(HIREDATE, 'MONTH') FROM EMP; 
SELECT ENAME, SYSDATE, HIREDATE, 
ROUND(ROUND(MONTHS_BETWEEN (SYSDATE, HIREDATE),2)/12,2)  FROM EMP; 
SELECT TO_DATE(810220,'YYMMDD') FROM DUAL;
SELECT TO_NUMBER('20,000', '9999999999') FROM DUAL; 

