SELECT MAX(HIREDATE),MIN(HIREDATE) FROM EMP;
SELECT COUNT(DISTINCT JOB) FROM EMP WHERE DEPTNO=30;
SELECT JOB FROM EMP WHERE DEPTNO=30;
SELECT DEPTNO,MAX(SAL) FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO, COUNT(*),COUNT(COMM) FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO,AVG(SAL) FROM EMP 
GROUP BY DEPTNO HAVING AVG(SAL)>=2000;